### ISSUE TITLE
No Supported in IE 11

### ISSUE THREAD

**Issue by Eireternal** [ie-web-notifications/ie-web-notifications#2]

**Comment by ie-web-notifications** [comment]
The issue looks invalid. If it does not work, could you please provide with more details (versions of OS, IE, and IE Web Notifications) and what in particular does not work?

**Comment by Eireternal** [comment]
I am using Windows 10 on IE 11 using version 0.9.0 for the notifications
found here: https://ie-web-notifications.github.io/

Landing on the page immediately tells me "_Notifications are not available_"

**Comment by ie-web-notifications** [comment]
Just in case could you please ensure that IE Web Notifications addon is enabled?

**Comment by ChannyAzar** [comment]
I'm also having problems with it.
From one computer I get the same error: "Notifications are not available"
From the second one, I added this site. and got PN. But I'm not getting PN for new emails.

**Comment by ie-web-notifications** [comment]
> From one computer I get the same error: "Notifications are not available"

Please ensure that the plugin installed and if it still does not work, could you please share the details, what versions of OS and the IE browser are used and whether the plugin is loaded?

> From the second one, I added this site. and got PN. But I'm not getting PN for new emails.

I guess PN refers to push notifications. If the notifications work on the web site https://ie-web-notifications.github.io/, then please double check the configuration of the e-mail, maybe one should firstly enable it there and request permission, additionally it can happen that the code of the e-mail interface detects the IE browser and does not even try to use the notification functionality. There is not so much one can do with it.
