### ISSUE TITLE
notification are not available, IE11 + Windows7

### ISSUE THREAD

**Issue by AsyShm** [ie-web-notifications/ie-web-notifications#5]
Hi,
I would like to use try this feature but seems not made available for IE11+Windows7.
could there be any settings needed to make it works? because I see that you have tested this in similar environment. should there be steps needed prior working on this, please help me to do it.
#IE11 #Windows7

thanks
regards,
asy

**Comment by ukot** [comment]
Hello,

In order to try and use it in Internet Explorer one has to firstly install the addon extending Internet Explorer with this functionality.

**Comment by jaoyina** [comment]
could you tell the addon name?

**Comment by ie-web-notifications** [comment]
This project is that addon.
